package device

// Human-readable RU/EN labels for the builder UI. Wording follows the Yandex
// docs (device-types, mode-instance(-modes), float/event/toggle-instance) so the
// terms match how Alice refers to them. Values stay technical; only display
// text is localized.

// Label is a bilingual display name.
type Label struct {
	Ru string `json:"ru"`
	En string `json:"en"`
}

// Labels groups display names by schema category, mirroring Schema.
type Labels struct {
	DeviceTypes     map[string]Label `json:"device_types"`
	Capabilities    map[string]Label `json:"capabilities"`
	Properties      map[string]Label `json:"properties"`
	RangeInstances  map[string]Label `json:"range_instances"`
	FloatInstances  map[string]Label `json:"float_instances"`
	ModeInstances   map[string]Label `json:"mode_instances"`
	ModeValues      map[string]Label `json:"mode_values"`
	EventInstances  map[string]Label `json:"event_instances"`
	EventValues     map[string]Label `json:"event_values"`
	ToggleInstances map[string]Label `json:"toggle_instances"`
	ColorInstances  map[string]Label `json:"color_instances"`
	ColorScenes     map[string]Label `json:"color_scenes"`
	Units           map[string]Label `json:"units"`
}

// BuildLabels returns the label dictionary served to the builder.
func BuildLabels() Labels { return labels }

func l(ru, en string) Label { return Label{Ru: ru, En: en} }

var labels = Labels{
	DeviceTypes: map[string]Label{
		"devices.types.sensor":                  l("Датчик", "Sensor"),
		"devices.types.sensor.button":           l("Умная кнопка", "Smart button"),
		"devices.types.sensor.climate":          l("Датчик климата", "Climate sensor"),
		"devices.types.sensor.gas":              l("Датчик газа", "Gas sensor"),
		"devices.types.sensor.illumination":     l("Датчик освещённости", "Illumination sensor"),
		"devices.types.sensor.motion":           l("Датчик движения", "Motion sensor"),
		"devices.types.sensor.open":             l("Датчик открытия", "Door sensor"),
		"devices.types.sensor.smoke":            l("Датчик дыма", "Smoke detector"),
		"devices.types.sensor.vibration":        l("Датчик вибрации", "Vibration sensor"),
		"devices.types.sensor.water_leak":       l("Датчик протечки", "Water leak sensor"),
		"devices.types.smart_meter":             l("Счётчик", "Meter"),
		"devices.types.smart_meter.cold_water":  l("Счётчик холодной воды", "Cold water meter"),
		"devices.types.smart_meter.electricity": l("Счётчик электроэнергии", "Electricity meter"),
		"devices.types.smart_meter.gas":         l("Счётчик газа", "Gas meter"),
		"devices.types.smart_meter.heat":        l("Счётчик тепла", "Heat meter"),
		"devices.types.smart_meter.hot_water":   l("Счётчик горячей воды", "Hot water meter"),
		"devices.types.camera":                  l("Видеокамера", "Video camera"),
		"devices.types.media_device":            l("Медиаустройство", "Media device"),
		"devices.types.media_device.receiver":   l("Ресивер", "Receiver"),
		"devices.types.media_device.tv":         l("Телевизор", "Smart TV"),
		"devices.types.media_device.tv_box":     l("ТВ-приставка", "TV set-top box"),
		"devices.types.cooking":                 l("Кухонная техника", "Kitchen appliance"),
		"devices.types.cooking.coffee_maker":    l("Кофеварка", "Coffee maker"),
		"devices.types.cooking.kettle":          l("Умный чайник", "Smart kettle"),
		"devices.types.cooking.multicooker":     l("Мультиварка", "Multicooker"),
		"devices.types.dishwasher":              l("Посудомоечная машина", "Dishwasher"),
		"devices.types.iron":                    l("Утюг", "Iron"),
		"devices.types.vacuum_cleaner":          l("Робот-пылесос", "Robot vacuum cleaner"),
		"devices.types.washing_machine":         l("Стиральная машина", "Washing machine"),
		"devices.types.pet_drinking_fountain":   l("Поилка", "Pet drinking fountain"),
		"devices.types.pet_feeder":              l("Кормушка", "Pet feeder"),
		"devices.types.humidifier":              l("Увлажнитель воздуха", "Humidifier"),
		"devices.types.purifier":                l("Очиститель воздуха", "Air purifier"),
		"devices.types.thermostat":              l("Термостат", "Thermostat"),
		"devices.types.thermostat.ac":           l("Кондиционер", "Air conditioner"),
		"devices.types.ventilation":             l("Вентиляция", "Ventilation system"),
		"devices.types.ventilation.fan":         l("Вентилятор", "Fan"),
		"devices.types.light":                   l("Лампочка", "Light"),
		"devices.types.light.lamp":              l("Настольная лампа", "Desk lamp"),
		"devices.types.light.ceiling":           l("Люстра", "Chandelier"),
		"devices.types.light.strip":             l("Светодиодная лента", "LED strip"),
		"devices.types.socket":                  l("Умная розетка", "Smart socket"),
		"devices.types.switch":                  l("Выключатель", "Switch"),
		"devices.types.switch.relay":            l("Реле", "Smart relay"),
		"devices.types.openable":                l("Дверь/окно", "Door/gate/window"),
		"devices.types.openable.curtain":        l("Шторы", "Curtains/blinds"),
		"devices.types.openable.door_lock":      l("Замок", "Lock"),
		"devices.types.openable.valve":          l("Шаровой кран", "Ball valve"),
		"devices.types.other":                   l("Другое устройство", "Other device"),
	},
	Capabilities: map[string]Label{
		"devices.capabilities.on_off":        l("Вкл/выкл", "On/off"),
		"devices.capabilities.color_setting": l("Настройка цвета", "Color setting"),
		"devices.capabilities.mode":          l("Режим", "Mode"),
		"devices.capabilities.range":         l("Диапазон", "Range"),
		"devices.capabilities.toggle":        l("Функция", "Toggle"),
		"devices.capabilities.video_stream":  l("Видеопоток", "Video stream"),
	},
	Properties: map[string]Label{
		"devices.properties.float": l("Числовой датчик", "Numeric sensor"),
		"devices.properties.event": l("Событие", "Event"),
	},
	RangeInstances: map[string]Label{
		"brightness":  l("Яркость", "Brightness"),
		"channel":     l("Канал", "Channel"),
		"humidity":    l("Влажность", "Humidity"),
		"open":        l("Открытие", "Opening"),
		"temperature": l("Температура", "Temperature"),
		"volume":      l("Громкость", "Volume"),
	},
	FloatInstances: map[string]Label{
		"amperage":          l("Сила тока", "Amperage"),
		"battery_level":     l("Заряд батареи", "Battery level"),
		"co2_level":         l("Уровень CO₂", "CO₂ level"),
		"electricity_meter": l("Счётчик электроэнергии", "Electricity meter"),
		"food_level":        l("Уровень корма", "Food level"),
		"gas_meter":         l("Счётчик газа", "Gas meter"),
		"heat_meter":        l("Счётчик тепла", "Heat meter"),
		"humidity":          l("Влажность", "Humidity"),
		"illumination":      l("Освещённость", "Illumination"),
		"meter":             l("Счётчик", "Meter"),
		"pm1_density":       l("Частицы PM1", "PM1 density"),
		"pm2.5_density":     l("Частицы PM2.5", "PM2.5 density"),
		"pm10_density":      l("Частицы PM10", "PM10 density"),
		"power":             l("Мощность", "Power"),
		"pressure":          l("Давление", "Pressure"),
		"temperature":       l("Температура", "Temperature"),
		"tvoc":              l("Летучие вещества (TVOC)", "TVOC"),
		"voltage":           l("Напряжение", "Voltage"),
		"water_level":       l("Уровень воды", "Water level"),
		"water_meter":       l("Счётчик воды", "Water meter"),
	},
	ModeInstances: map[string]Label{
		"cleanup_mode":     l("Режим уборки", "Cleaning mode"),
		"coffee_mode":      l("Режим кофеварки", "Coffee mode"),
		"dishwashing":      l("Режим мойки", "Dishwashing mode"),
		"fan_speed":        l("Скорость вентиляции", "Fan speed"),
		"heat":             l("Режим нагрева", "Heating mode"),
		"input_source":     l("Источник сигнала", "Input source"),
		"program":          l("Программа", "Program"),
		"swing":            l("Направление воздуха", "Air direction"),
		"tea_mode":         l("Режим чая", "Tea mode"),
		"thermostat":       l("Температурный режим", "Thermostat mode"),
		"ventilation_mode": l("Режим вентиляции", "Ventilation mode"),
		"work_speed":       l("Скорость работы", "Work speed"),
	},
	ModeValues: map[string]Label{
		"wet_cleaning":    l("Влажная уборка", "Wet cleaning"),
		"dry_cleaning":    l("Сухая уборка", "Dry cleaning"),
		"mixed_cleaning":  l("Смешанная уборка", "Mixed cleaning"),
		"auto":            l("Автоматический", "Automatic"),
		"eco":             l("Экономичный", "Economy"),
		"smart":           l("Умный", "Smart"),
		"turbo":           l("Турбо", "Turbo"),
		"cool":            l("Охлаждение", "Cooling"),
		"dry":             l("Осушение", "Drying"),
		"fan_only":        l("Вентиляция", "Ventilation"),
		"heat":            l("Обогрев", "Heating"),
		"preheat":         l("Подогрев", "Pre-heating"),
		"high":            l("Высокая скорость", "High speed"),
		"low":             l("Низкая скорость", "Low speed"),
		"medium":          l("Средняя скорость", "Medium speed"),
		"max":             l("Максимальный", "Maximum"),
		"min":             l("Минимальный", "Minimum"),
		"fast":            l("Быстрый", "Fast"),
		"slow":            l("Медленный", "Slow"),
		"express":         l("Экспресс", "Express"),
		"normal":          l("Нормальный", "Normal"),
		"quiet":           l("Тихий", "Quiet"),
		"horizontal":      l("Горизонтальный", "Horizontal"),
		"stationary":      l("Неподвижный", "Fixed"),
		"vertical":        l("Вертикальный", "Vertical"),
		"supply_air":      l("Приток воздуха", "Air supply"),
		"extraction_air":  l("Отток воздуха", "Air extraction"),
		"one":             l("Первый", "First"),
		"two":             l("Второй", "Second"),
		"three":           l("Третий", "Third"),
		"four":            l("Четвёртый", "Fourth"),
		"five":            l("Пятый", "Fifth"),
		"six":             l("Шестой", "Sixth"),
		"seven":           l("Седьмой", "Seventh"),
		"eight":           l("Восьмой", "Eighth"),
		"nine":            l("Девятый", "Ninth"),
		"ten":             l("Десятый", "Tenth"),
		"americano":       l("Американо", "Americano"),
		"cappuccino":      l("Капучино", "Cappuccino"),
		"double_espresso": l("Двойной эспрессо", "Double espresso"),
		"espresso":        l("Эспрессо", "Espresso"),
		"latte":           l("Латте", "Latte"),
		"black_tea":       l("Чёрный чай", "Black tea"),
		"flower_tea":      l("Цветочный чай", "Flower tea"),
		"green_tea":       l("Зелёный чай", "Green tea"),
		"herbal_tea":      l("Травяной чай", "Herbal tea"),
		"oolong_tea":      l("Чай улун", "Oolong tea"),
		"puerh_tea":       l("Чай пуэр", "Pu-erh tea"),
		"red_tea":         l("Красный чай", "Red tea"),
		"white_tea":       l("Белый чай", "White tea"),
		"glass":           l("Мойка стекла", "Glass washing"),
		"intensive":       l("Интенсивный", "Intensive"),
		"pre_rinse":       l("Ополаскивание", "Rinsing"),
		"aspic":           l("Холодец", "Aspic"),
		"baby_food":       l("Детское питание", "Baby food"),
		"baking":          l("Выпечка", "Bake"),
		"bread":           l("Хлеб", "Bread"),
		"boiling":         l("Варка", "Boil"),
		"cereals":         l("Крупы", "Grains"),
		"cheesecake":      l("Чизкейк", "Cheesecake"),
		"deep_fryer":      l("Фритюр", "Deep-fry"),
		"dessert":         l("Десерты", "Dessert"),
		"fowl":            l("Дичь", "Poultry"),
		"frying":          l("Жарка", "Fry"),
		"macaroni":        l("Макароны", "Macaroni"),
		"milk_porridge":   l("Молочная каша", "Milk porridge"),
		"multicooker":     l("Мультиповар", "Multicook"),
		"pasta":           l("Паста", "Pasta"),
		"pilaf":           l("Плов", "Pilaf"),
		"pizza":           l("Пицца", "Pizza"),
		"sauce":           l("Соус", "Sauce"),
		"slow_cook":       l("Томление", "Slow cook"),
		"soup":            l("Суп", "Soup"),
		"steam":           l("Пар", "Steam"),
		"stewing":         l("Тушение", "Stew"),
		"vacuum":          l("Вакуум", "Vacuum"),
		"yogurt":          l("Йогурт", "Yogurt"),
	},
	EventInstances: map[string]Label{
		"vibration":     l("Вибрация", "Vibration"),
		"open":          l("Открытие/закрытие", "Opening"),
		"button":        l("Нажатие кнопки", "Button press"),
		"motion":        l("Движение", "Motion"),
		"smoke":         l("Дым", "Smoke"),
		"gas":           l("Газ", "Gas"),
		"battery_level": l("Заряд батареи", "Battery charge"),
		"food_level":    l("Уровень корма", "Food level"),
		"water_level":   l("Уровень воды", "Water level"),
		"water_leak":    l("Протечка воды", "Water leak"),
	},
	EventValues: map[string]Label{
		"tilt":         l("Переворачивание", "Tilting"),
		"fall":         l("Падение", "Falling"),
		"vibration":    l("Вибрация", "Vibrating"),
		"opened":       l("Открыто", "Open"),
		"closed":       l("Закрыто", "Closed"),
		"click":        l("Одиночное нажатие", "Single press"),
		"double_click": l("Двойное нажатие", "Double press"),
		"long_press":   l("Долгое нажатие", "Long press"),
		"detected":     l("Обнаружено", "Detected"),
		"not_detected": l("Не обнаружено", "Not detected"),
		"high":         l("Высокий уровень", "High level"),
		"low":          l("Низкий", "Low"),
		"normal":       l("Нормальный", "Normal"),
		"empty":        l("Пустой", "Empty"),
		"dry":          l("Нет протечки", "No leak"),
		"leak":         l("Протечка", "Leak"),
	},
	ToggleInstances: map[string]Label{
		"backlight":       l("Подсветка", "Backlight"),
		"controls_locked": l("Блокировка управления", "Controls locked"),
		"ionization":      l("Ионизация", "Ionization"),
		"keep_warm":       l("Поддержание тепла", "Keep warm"),
		"mute":            l("Без звука", "Mute"),
		"oscillation":     l("Вращение", "Oscillation"),
		"pause":           l("Пауза", "Pause"),
	},
	ColorInstances: map[string]Label{
		"hsv":           l("Цвет (HSV)", "Color (HSV)"),
		"rgb":           l("Цвет (RGB)", "Color (RGB)"),
		"temperature_k": l("Температура света", "Color temperature"),
		"scene":         l("Сцена", "Scene"),
	},
	ColorScenes: map[string]Label{
		"alarm":   l("Тревога", "Alarm"),
		"alice":   l("Алиса", "Alice"),
		"candle":  l("Свеча", "Candle"),
		"dinner":  l("Ужин", "Dinner"),
		"fantasy": l("Фантазия", "Fantasy"),
		"garland": l("Гирлянда", "Garland"),
		"jungle":  l("Джунгли", "Jungle"),
		"movie":   l("Кино", "Movie"),
		"neon":    l("Неон", "Neon"),
		"night":   l("Ночь", "Night"),
		"ocean":   l("Океан", "Ocean"),
		"party":   l("Вечеринка", "Party"),
		"reading": l("Чтение", "Reading"),
		"rest":    l("Отдых", "Rest"),
		"romance": l("Романтика", "Romance"),
		"siren":   l("Сирена", "Siren"),
	},
	Units: map[string]Label{
		"unit.percent":             l("%", "%"),
		"unit.temperature.celsius": l("°C", "°C"),
		"unit.temperature.kelvin":  l("K", "K"),
		"unit.ampere":              l("А", "A"),
		"unit.kilowatt_hour":       l("кВт·ч", "kWh"),
		"unit.cubic_meter":         l("м³", "m³"),
		"unit.gigacalorie":         l("Гкал", "Gcal"),
		"unit.illumination.lux":    l("лк", "lx"),
		"unit.density.mcg_m3":      l("мкг/м³", "µg/m³"),
		"unit.watt":                l("Вт", "W"),
		"unit.volt":                l("В", "V"),
		"unit.ppm":                 l("ppm", "ppm"),
		"unit.pressure.atm":        l("атм", "atm"),
		"unit.pressure.pascal":     l("Па", "Pa"),
		"unit.pressure.bar":        l("бар", "bar"),
		"unit.pressure.mmhg":       l("мм рт. ст.", "mmHg"),
	},
}
